version: 1
updates:
  - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "daily"
      allow:
        - dependency-type: "all"
    automerged_updates:
      - match:
        dependency_type: "all"
        update_type: "all"
    version_requirement_updates: "widen_ranges"
